services:
  app:
    build: ./php
    container_name: oooonly-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9003:9003" # Xdebug
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: oooonly-nginx
    ports:
      - "8091:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: oooonly-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: pavel
      MYSQL_PASSWORD: pavelpavel
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: oooonly-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
